### ISSUE TITLE
控制台插件模板仍然使用 `using` 而不是 `inject`  

### ISSUE THREAD

**Issue by CyanChanges** [koishijs/scripts#7]
#6 
![image](https://github.com/koishijs/scripts/assets/68551684/cbc35c9e-29c8-4fbb-8b65-031d44525115)

**Comment by CyanChanges** [comment]
是不是可以顺便把 
导入的 `@koishijs/plugin-console` 类型
给换成 
`@koishijs/console`

**Comment by shigma** [comment]
Fixed

**Comment by shigma** [comment]
> 是不是可以顺便把 导入的 `@koishijs/plugin-console` 类型 给换成 `@koishijs/console`

这个先不改吧，未来可能改回来，不太好说
